### ISSUE TITLE
[feat] Coordinator

### ISSUE THREAD

**Issue by ezidayzi** [bbangmap/BBangMap-iOS#17]
## 개요
Coordinator 패턴을 적용하기 위한 틀을 마련합니다

참고자료
https://jintaewoo.tistory.com/58
https://duwjdtn11.tistory.com/m/645?category=1112975
https://khanlou.com/2015/10/coordinators-redux/

### 기능
- [x] Coordinator 추가 후 AppCoordinator 생성
- [x] Tabbar Coordinator 적용

**Comment by 5anniversary** [comment]
👍
