### ISSUE TITLE
[feat] 회원가입 뷰 

### ISSUE THREAD

**Issue by havetherain** [bbangmap/BBangMap-iOS#18]
## 개요
- 회원가입을 위한 닉네임 작성창과 가입 완료 화면을 구현한다

### 레이아웃
- [x] 회원가입 뷰 화면 구현
- [ ] 회원가입 기능 구현

**Comment by 5anniversary** [comment]
마일스톤도 찍어주세요~

**Comment by havetherain** [comment]
> 마일스톤도 찍어주세요~

계획 수립되면 적을게요~

**Comment by 5anniversary** [comment]
:페페_굿:
